// Solution-6.scala
// Solution to Exercise 6 in "Error Handling with Exceptions"
import com.atomicscala.AtomicTest._

/*{oldDescription}
6.	Create a class with two methods, f and g. In g, throw a new type of exception that you define. In f, call g, catch its exception and, in the catch clause, throw a different exception (of a second type that you define). Test your code.
{oldDescription}*/

// needs solution
